# Generated by Django 5.0.3 on 2026-08-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('project_view', 'Project View'), ('github_view', 'GitHub View'), ('contact_submit', 'Contact Submit'), ('page_view', 'Page View')], max_length=50)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, help_text='Anonymized hash to count unique visitors without PII', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_p_event_t_4660e9_idx')],
            },
        ),
    ]
